# Model parameters
model: videomae_classifier_small_patch16_224
ckpt_path: [
  /path/to/pretrain/rgb.pt,
  /path/to/pretrain/flow.pt,
  /path/to/pretrain/pose.pt
]
in_chans: [3, 2, 21]
use_mean_pooling: True
encoder_embed_dim: 384

# Optimizer parameters
epochs: 100

opt: adamw
opt_eps: 1e-8
opt_betas: [0.9, 0.999]
clip_grad:
momentum: 0.9
weight_decay: 0.05

lr: 2e-3
warmup_lr: 1e-6
min_lr: 1e-6
warmup_epochs: 5
use_checkpoint: False
