# Target Dataset
# WEAR
target_dataset: WEAR
target_data_dir: /data/WEAR/
fewshot_eval_json_path: /cdfsl/target/wear/annotations/wear_val.json
unlabel_json_path: /cdfsl/target/wear/annotations/wear_unlabel.json
target_sampling_rate: 8